import Cookies from 'js-cookie'
import type { Metadata } from "next";

import '@/index.css'
import { StrictMode } from 'react';
import { ThemeProvider } from '@/context/theme-context';

export const metadata: Metadata = {
  title: "Shadcn Admin Next",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const defaultOpen = Cookies.get('sidebar:state') !== 'false'
  // FOR INSECURE SSL (ex: Self Signed Certificates)
  
  return (
    <html lang="en">
      <body className="group/body">
        {/* <StrictMode> */}
          {/* <AuthProvider session={session}> */}
            <ThemeProvider defaultTheme='light' storageKey='ui-theme'>
              {children}
            </ThemeProvider>
          {/* </AuthProvider> */}
        {/* </StrictMode> */}
      </body>
    </html>
  );
}
